extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MSEObserver
        a_observer: EMAMSEObserver
        w_fakequantize: AdaRoundFakeQuantize
        a_fakequantize: QDropFakeQuantize
        w_qscheme:
            bit: 8
            symmetry: True
            per_channel: False
            pot_scale: True
            p: 2.4
        a_qscheme:
            bit: 8
            symmetry: True
            per_channel: False
            pot_scale: True
            p: 2.4
    deploy:
        output_path: onnx_models
        model_name: mbv2_brecq_ti
quantize:
    backend: Ti
    quantize_type: advanced_ptq # support naive_ptq or advanced_ptq
    cali_batchsize: 1
    reconstruction:
        pattern: block
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.1
        max_count: 20000
        b_range: [20,2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        prob: 1.0
    # deploy:
    #     output_path: onnx_models
    #     model_name: res18_hipu
model:                    # architecture details
    type: mobilenet_v2        # model name
    kwargs:
        num_classes: 1000
data:
    path: /data/renyan/datasets/imagenet
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005






# mobilenet_v2
#  * Acc@1 71.870 Acc@5 90.294 fp32 torchvision 
#  * Acc@1 70.918 Acc@5 89.904 int8 qdrop
#  * Acc@1 70.582 Acc@5 89.850 int8 brecq