quantize:
    backend: Ti
    quantize_type: naive_ptq # support naive_ptq or advanced_ptq
    cali_batchsize: 16
    # deploy:
    #     output_path: onnx_models
    #     model_name: res18_ti
model:                    # architecture details
    type: resnet18        # model name
    kwargs:
        num_classes: 1000
    path: /home/ry/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
data:
    path: /data/renyan/datasets/imagenet
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005